name: Build VLC-Android Debug APK
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - name: Enable KVM group perms
        run: >
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666",
          OPTIONS+="static_node=kvm"' | sudo tee
          /etc/udev/rules.d/99-kvm4all.rules

          sudo udevadm control --reload-rules

          sudo udevadm trigger --name-match=kvm
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          ndk: 25.1.8937393
      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > medialibrary/local.properties
        working-directory: ./
      - name: Grant Permissions to Gradle Wrapper
        run: chmod +x gradlew
        working-directory: ./
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: >-
            ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*',
            '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build Debug APK and Test APK
        run: >-
          ./gradlew :application:vlc-android:assembleDebug
          :application:vlc-android:assembleDebugAndroidTest --stacktrace
        working-directory: ./
      - name: Start Emulator and Install APKs
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          arch: x86_64
          profile: Nexus 6
          script: |
            echo "Emulator started"

            adb install -t application/app/build/outputs/apk/debug/VLC-Android-3.6.4-Beta-3-debug-all.apk

            adb install -t application/vlc-android/build/outputs/apk/androidTest/debug/vlc-android-debug-androidTest.apk
            ./gradlew :application:vlc-android:connectedDebugAndroidTest --stacktrace --max-workers 2 -Pandroid.testInstrumentationRunnerArguments.numShards=4

            adb shell am force-stop org.videolan.vlc
            adb emu kill
        timeout-minutes: 15
